#!/bin/bash
# A script to open firefox to the URL of "Never Gonna Give You Up" by Rick Astley and click the center of the screen to play.
# For even more fun put this on your friend's computer and set a cronjob ;).
# You need to have firefox and xdotool installed on your computer for this to work.

firefox --new-window https://www.youtube.com/watch?v=dQw4w9WgXcQ &

sleep 5

xdotool search "Mozilla Firefox" key space
