#!/usr/bin/env bash
#
# Toggle ssh server on or off. If no args are given ssh server status is displayed.
#

if [ "$*" = "on" ]; then
    sudo systemctl start ssh
    sudo systemctl status ssh | grep Active
elif [ "$*" = "off" ]; then
    sudo systemctl stop ssh
    sudo systemctl status ssh | grep Active
elif [ -z "$*" ]; then
    sudo systemctl status ssh | grep Active
else
    echo "toggle-ssh: unknown option -- $*"
fi