#!/bin/bash
# A script to update my docker-compose files from a private repository and run docker-compose on them.

# standard server
standard_config () {
    local padding_length="$(($((64-${#1}))/2))"
    for i in $(seq 1 $padding_length)
    do
        local padding+="-"
    done
    echo "$padding$1$padding"
    cd Docker-Composes
    echo "Pulling..."
    git pull
    echo "Copying..."
    cp $1/docker-compose.yml ~/docker/docker-compose.yml
    cp $1/.env  ~/docker/.env
    cd ~/docker
    echo "Running docker-compose..."
    docker-compose up -d
}

# ssh into servers to run functions
if [ $# -eq 0 ]; then
    echo "---------------------Updating compose files---------------------"
    echo "No arguments specified, so updating all"
    ssh administrator@phobos "$(typeset -f standard_config); standard_config phobos"
    ssh administrator@deimos "$(typeset -f standard_config); standard_config deimos"

else
    echo "--------------------Updating compose file(s)--------------------"
    declare -a invalid_servers
    for param in "$@"
    do
        if [ "$param" == "phobos" ]; then
            ssh administrator@phobos "$(typeset -f standard_config); standard_config phobos"

        elif [ "$param" == "deimos" ]; then
            ssh administrator@deimos "$(typeset -f standard_config); standard_config deimos"

        fi
    done
fi
