#
# ~/.zshrc
#

source "$HOME/.zsh/env.zsh"
source "$HOME/.zsh/zsh_config.zsh"
source "$HOME/.zsh/external.zsh"
source "$HOME/.zsh/functions.zsh"
source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/path.zsh"

# Added by Antigravity
export PATH="/Users/gideonshaked/.antigravity/antigravity/bin:$PATH"
