# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Allow local customizations in the ~/.bashrc_local_before file
if [ -f "$HOME/.bashrc_local_before" ]; then
    source "$HOME/.bashrc_local_before"
fi

source "$HOME/.settings.bash"

source "$HOME/.functions.bash"

source "$HOME/.aliases.bash"

source "$HOME/.path.bash"

source "$HOME/.external.bash"

source "$HOME/.prompt.bash"

source "$HOME/.completions/*"

# Allow local customizations in the ~/.bashrc_local_after file
if [ -f "$HOME/.bashrc_local_after" ]; then
    source "$HOME/.bashrc_local_after"
fi
