#!/bin/bash
# A script to update my docker-compose files from a private repository and run docker-compose on them.

# phobos server - needs a special function due to differences in configuration
phobos_config () {
    echo "-----------------------------phobos-----------------------------"
    cd Docker-Composes
    echo "Pulling..."
    git pull git@github.com:The-Kid-Gid/Docker-Composes.git
    echo "Copying..."
    cp phobos/docker-compose.yml ~/docker/docker-compose.yml
    cp phobos/environment /etc/environment
    cd ~/docker
    echo "Running docker-compose..."
    docker-compose up -d
}

# standard server
standard_config () {
    local padding_length="$(($((64-${#1}))/2))"
    for i in $(seq 1 $padding_length)
    do
        local padding+="-"
    done
    echo "$padding$1$padding"
    cd Docker-Composes
    echo "Pulling..."
    git pull git@github.com:The-Kid-Gid/Docker-Composes.git
    echo "Copying..."
    cp $1/docker-compose.yml ~/docker/docker-compose.yml
    cp $1/.env  ~/docker/.env
    cd ~/docker
    echo "Running docker-compose..."
    docker-compose up -d
}

# ssh into servers to run functions
if [ $# -eq 0 ]; then
    echo "---------------------Updating compose files---------------------"
    echo "No arguments specified, so updating all"
    ssh administrator@phobos "$(typeset -f phobos_config); phobos_config"
    ssh pi@deimos "$(typeset -f standard_config); standard_config deimos"
    ssh administrator@styx "$(typeset -f standard_config); standard_config styx"

else
    echo "--------------------Updating compose file(s)--------------------"
    declare -a invalid_servers
    for param in "$@"
    do
        if [ "$param" == "phobos" ]; then
            ssh administrator@phobos "$(typeset -f phobos_config); phobos_config"

        elif [ "$param" == "deimos" ]; then
            ssh pi@deimos "$(typeset -f standard_config); standard_config deimos"

        elif [ "$param" == "styx" ]; then
            ssh administrator@styx "$(typeset -f standard_config); standard_config styx"

        else
            invalid_servers+=( "$param" )

        fi
    done

    if [ "${#invalid_servers[@]}" > 0 ]; then
        echo "----------------------------------------------------------------"
        echo -n "The parameter(s) "
        for invalid_server in "${invalid_servers[@]}"
        do
            echo -n "$invalid_server, "
        done
        echo "is/are invalid."
    fi
fi
