#!/usr/bin/env bash
#
# Import extensions from vscode/extensions.txt to Vscode.
#

extensions="vscode/extensions.txt"
while IFS= read -r ext
do
    code --install-extension "$ext"
done < "$extensions"
