#!/usr/bin/env bash
#
# Import extensions from vscode/extensions.txt to VS code.
#

not_installed_exts() {
    local extensions=$(cat "vscode/extensions.txt")
    local current_extensions=$(code --list-extensions)
    extensions_not_installed=$(diff --new-line-format="" --unchanged-line-format="" <(echo "$current_extensions") <(echo "$extensions"))
}

install_exts() {
    while IFS= read -r extension; do
        code --install-extension "$extension"
    done <<< "$1"
}

main() {
    not_installed_exts

    install_exts "$extensions_not_installed"
}

main