#!/usr/bin/env bash
#
# Get Starship from S3
# Run this script with sudo
#

curl https://starship-arm.s3.amazonaws.com/starship --output starship

chmod +x ./starship

mv ./starship /usr/local/bin/starship