#!/usr/bin/env bash
#
# (aup = Apt UPdate)
# Script to ssh into remote servers and update system
#

run_cmds() {
    ssh "administrator@${1}" "
        echo "Updating..."
        sudo apt-get update -y && sudo apt-get upgrade -y
    "
}

parse_args() {
    if [[ -n "$1" ]]; then
        SERVERS="$1"
        echo "Using provided server names: ${SERVERS}"
    else
        SERVERS=("phobos" "deimos")
        echo "Using default server names: ${SERVERS[*]}"
    fi
}

main() {
    parse_args "$1"

    for server in "${SERVERS[@]}"; do
        echo
        echo "----------${server}----------"
        run_cmds "$server"
    done
}

main "$@"
