#!/usr/bin/env bash
#
# Set up SSH key login on server
#

if [[ -z "${2}"  ]]; then
    algo="ed25519"
else
    algo="${2}"
fi
set -o xtrace
ssh-keygen  -t "${algo}" -f "$HOME/.ssh/${1}_key"
ssh-copy-id -i "$HOME/.ssh/${1}_key.pub" "${1}"
